"""Kryphorix Firewall & WAF Detection Module."""
import socket
import re
import requests
from core.finding import Finding
from core.findings import FindingsManager

try:
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except Exception:
    pass
import logging
logger = logging.getLogger("kryphorix")

WAF_SIGS = {
    "Cloudflare":         {"headers": ["cf-ray","cf-cache-status"], "body": ["cloudflare"], "server": ["cloudflare"]},
    "AWS WAF":            {"headers": ["x-amzn-requestid","x-amz-cf-id"], "body": ["aws waf"], "server": []},
    "Akamai":             {"headers": ["x-akamai-transformed","akamai-origin-hop"], "body": [], "server": ["akamaighost"]},
    "Imperva/Incapsula":  {"headers": ["x-iinfo"], "body": ["incapsula incident"], "server": ["incapsula"]},
    "F5 BIG-IP":          {"headers": [], "body": ["bigip","the requested url was rejected"], "server": ["bigip"]},
    "Sucuri":             {"headers": ["x-sucuri-id"], "body": ["access denied - sucuri"], "server": ["sucuri"]},
    "ModSecurity":        {"headers": [], "body": ["modsecurity","406 not acceptable"], "server": ["mod_security"]},
    "Barracuda":          {"headers": ["barra_counter_session"], "body": ["barracuda"], "server": []},
    "Fortinet FortiWeb":  {"headers": ["fortiweb"], "body": ["fortiweb application firewall"], "server": ["fortiweb"]},
    "Wordfence":          {"headers": [], "body": ["generated by wordfence"], "server": []},
    "Fastly":             {"headers": ["x-fastly-request-id"], "body": [], "server": ["varnish"]},
    "Cloudfront":         {"headers": ["x-amz-cf-id","x-amz-cf-pop"], "body": [], "server": ["cloudfront"]},
    "Nginx WAF/NAXSI":    {"headers": [], "body": ["naxsi_sig"], "server": ["naxsi"]},
}


def _get(session, url, **kw):
    try:
        kw.setdefault("timeout", 8)
        kw.setdefault("verify", False)
        return session.get(url, **kw)
    except Exception:
        return None


def scan(target: str, **kwargs) -> list:
    fm = FindingsManager()
    if not target.startswith("http"):
        target = "https://" + target
    host = re.sub(r"https?://", "", target).split("/")[0].split(":")[0]

    session = requests.Session()
    session.headers["User-Agent"] = "Mozilla/5.0 Kryphorix/4.0"

    r = _get(session, target)
    if r is None:
        fm.add(Finding(title="Target Unreachable", severity="Info",
                       description=f"Cannot reach {target}", remediation="Check target.", module="Firewall"))
        return fm.all()

    hdrs_lower = {k.lower(): v.lower() for k, v in r.headers.items()}
    body_lower = r.text.lower()

    detected = []
    for waf, sigs in WAF_SIGS.items():
        score = 0
        for h in sigs["headers"]:
            if h in hdrs_lower:
                score += 2
        for b in sigs["body"]:
            if b in body_lower:
                score += 1
        for s in sigs["server"]:
            if s in hdrs_lower.get("server", ""):
                score += 2
        if score >= 2:
            detected.append((waf, score))

    if detected:
        detected.sort(key=lambda x: x[1], reverse=True)
        top = detected[0][0]
        summary = ", ".join(f"{w}" for w, _ in detected)
        fm.add(Finding(
            title=f"WAF Detected: {top}",
            severity="Info",
            description=f"Web Application Firewall detected: {summary}",
            remediation="Ensure WAF rules are current. Consider WAF bypass testing.",
            module="Firewall",
            evidence=f"Detected: {summary}"
        ))

        # WAF bypass test
        bypass_payloads = ["/?q=<sCrIpT>alert(1)</sCrIpT>", "/?id=1' OR '1'='1",
                           "/..%2f..%2f..%2fetc%2fpasswd"]
        bypassed = []
        for payload in bypass_payloads:
            rb = _get(session, target.rstrip("/") + payload)
            if rb and rb.status_code not in [403, 406, 429, 503]:
                bypassed.append(payload)

        if bypassed:
            fm.add(Finding(
                title=f"Potential WAF Bypass ({top})",
                severity="High",
                description=f"WAF did not block {len(bypassed)} attack payloads.",
                remediation="Review WAF rules. Enable strict blocking mode.",
                module="Firewall", cvss=7.5,
                evidence="\n".join(bypassed)
            ))
    else:
        fm.add(Finding(
            title="No WAF Detected",
            severity="Medium",
            description="No WAF signatures found in response.",
            remediation="Consider deploying a WAF (Cloudflare, AWS WAF, ModSecurity).",
            module="Firewall", cvss=4.0
        ))

    # Network-level firewall detection
    test_ports = [21, 23, 25, 445, 3306, 5432, 6379, 27017]
    filtered = []
    for p in test_ports:
        s = socket.socket()
        s.settimeout(1.5)
        r2 = s.connect_ex((host, p))
        s.close()
        if r2 not in [0, 111]:
            filtered.append(p)

    if len(filtered) >= 4:
        fm.add(Finding(
            title=f"Network Firewall Detected ({len(filtered)} filtered ports)",
            severity="Info",
            description="Host silently drops connections to common ports — firewall present.",
            remediation="Verify firewall rules are appropriately configured.",
            module="Firewall",
            evidence=f"Filtered ports: {filtered}"
        ))

    # Rate limiting
    codes = []
    for _ in range(15):
        rb = _get(session, target)
        if rb:
            codes.append(rb.status_code)
    if 429 in codes:
        fm.add(Finding(
            title="Rate Limiting Active",
            severity="Info",
            description="Server enforces rate limiting (HTTP 429).",
            remediation="Ensure limits protect against brute force and DoS.",
            module="Firewall"
        ))
    elif codes and all(c == 200 for c in codes):
        fm.add(Finding(
            title="No Rate Limiting Detected",
            severity="Low",
            description="No rate limiting after 15 rapid requests.",
            remediation="Implement rate limiting on all endpoints.",
            module="Firewall", cvss=3.7
        ))

    return fm.all()
